window.__ModuleLoader__.load({id:'dsh-knowledge-work',factory:require=>{
 const React=require('react'),h=React.createElement
 const status={active:'進行中',blocked:'已暫停',completed:'已完成',cancelled:'已取消'}
 const modes={research:'研究整理',decision:'方案比較',maintenance:'知識維護'}
 const stages={plan:'拆解工作',research:'蒐集證據',analysis:'分析整理',writing:'整理交付',verification:'核查',review:'整體核查',deliver:'準備交付',blocked:'已暫停',completed:'已完成',cancelled:'已取消'}
 const css='.kw{font-family:system-ui,Microsoft JhengHei,sans-serif;font-size:14px;width:100%;height:100%;overflow:auto;padding:24px;box-sizing:border-box;color:inherit}.kw header{display:flex;align-items:center;gap:16px;margin-bottom:20px}.kw h1{font-size:22px;margin:0}.kw small{opacity:.7}.kw-grid{display:grid;grid-template-columns:260px minmax(0,1fr);gap:22px}.kw-list{position:sticky;top:0;align-self:start;display:flex;flex-direction:column;gap:8px}.kw button{font:inherit;cursor:pointer;color:inherit;background:transparent;border:1px solid #8885;border-radius:8px;padding:9px 12px;text-align:left}.kw button[aria-current=true]{border-color:#7b8bca;background:#7b8bca18}.kw-list button{display:flex;flex-direction:column;gap:6px}.kw section{border:1px solid #8884;border-radius:10px;padding:16px;margin-bottom:14px}.kw h2{font-size:16px;margin:0 0 12px}.kw p{white-space:pre-wrap;line-height:1.55}.kw ul{padding-left:20px}.kw li{margin:8px 0;line-height:1.5}.kw pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:420px;overflow:auto;font-size:12px}.kw details{padding:9px 0;border-bottom:1px solid #8883}.kw summary{cursor:pointer}.kw code{overflow-wrap:anywhere}.kw a{color:#718dd9}.kw-error{color:#c95c5c}.kw-meta{display:flex;gap:14px;flex-wrap:wrap;margin-bottom:14px}@media(max-width:720px){.kw-grid{grid-template-columns:1fr}}'
 async function api(query='',signal){const response=await fetch('/api/knowledge-work'+query,{signal});const text=await response.text();let value;try{value=JSON.parse(text)}catch{throw new Error('知識工作服務尚未就緒（HTTP '+response.status+'）')}if(!response.ok||!value.ok)throw new Error(value.error||'讀取失敗');return value}
 function Workbench(){
  const [tasks,setTasks]=React.useState([]),[selected,setSelected]=React.useState(''),[task,setTask]=React.useState(null),[sources,setSources]=React.useState({}),[error,setError]=React.useState(''),[revision,setRevision]=React.useState(0)
  React.useEffect(()=>{const controller=new AbortController();let stopped=false
   const refresh=async()=>{try{const result=await api('',controller.signal);if(stopped)return;setTasks(result.tasks);if(selected){const detail=await api('?task='+encodeURIComponent(selected),controller.signal);if(!stopped)setTask(detail.task)}setError('')}catch(e){if(!stopped&&e.name!=='AbortError')setError(e.message)}}
   void refresh();const timer=setInterval(refresh,3000);return()=>{stopped=true;controller.abort();clearInterval(timer)}
  },[selected,revision])
  function select(id){setSelected(id);setTask(null);setSources({})}
  async function readSource(id){try{const result=await api('?task='+encodeURIComponent(selected)+'&source='+encodeURIComponent(id));setSources(current=>({...current,[id]:result.sourceText}))}catch(e){setError(e.message)}}
  return h('div',{className:'kw'},h('style',null,css),h('header',null,h('h1',null,'知識工作'),h('small',null,'問題、來源、論點與交付進度'),h('button',{onClick:()=>setRevision(n=>n+1)},'重新整理')),error?h('p',{className:'kw-error',role:'alert'},error):null,
   h('div',{className:'kw-grid'},h('aside',{className:'kw-list'},tasks.length?tasks.map(item=>h('button',{key:item.id,'aria-current':selected===item.id,onClick:()=>select(item.id)},h('strong',null,item.title),h('small',null,modes[item.mode]+' · '+(stages[item.stage]||status[item.status])+' · '+item.progress.completed+'/'+item.progress.total))):h('p',null,'在新對話選擇「知識工作」Agent，再交付研究或整理任務。')),
    h('article',null,!selected?h('section',null,h('h2',null,'將知識工作交給 Agent'),h('p',null,'可以要求研究一個問題、比較方案，或更新已有知識。Agent 會保存工作步驟、實際讀取的來源、引用依據與尚未確認事項。'),h('p',null,'選擇左側工作案查看進度。需要暫停、恢復或變更範圍時，在對話中告訴 Agent。')):!task?h('p',null,'正在讀取工作案…'):h(React.Fragment,null,
     h('section',null,h('h2',null,task.title),h('div',{className:'kw-meta'},h('span',null,modes[task.mode]),h('span',null,status[task.status]),h('span',null,'版本 '+task.revision)),h('p',null,task.objective),task.scope?h('p',null,'範圍：'+task.scope):null,task.reason?h('p',null,'待處理：'+task.reason):null,h('small',null,'工作區：'+task.workspace)),
     h('section',null,h('h2',null,'交付條件'),h('ul',null,task.requirements.map(r=>h('li',{key:r.id},r.id+' · '+r.text)))),
     h('section',null,h('h2',null,'工作步驟'),task.steps.length?h('ol',null,task.steps.map(s=>h('li',{key:s.id},h('strong',null,({pending:'待執行',running:'進行中',done:'完成',blocked:'受阻'}[s.status])+' · '+s.title),s.note?h('p',null,s.note):null,s.dependsOn.length?h('small',null,'相依：'+s.dependsOn.join('、')):null))):h('p',null,'尚未拆解工作。')),
     h('section',null,h('h2',null,'來源'),task.sources.length?task.sources.map(s=>h('details',{key:s.id},h('summary',null,s.title+(s.supersededBy?' · 已有更新來源':'')),h('p',null,h('code',null,s.locator)),h('small',null,'擷取：'+s.capturedAt+'；原始讀取：'+(s.observedAt||'未提供')),h('p',null,s.scope||'適用範圍未標註'),h('button',{onClick:()=>readSource(s.id)},'查看已擷取原文'),sources[s.id]!==undefined?h('pre',null,sources[s.id]):null)):h('p',null,'尚未擷取來源。')),
     h('section',null,h('h2',null,'論點與證據'),task.claims.length?task.claims.map(c=>h('details',{key:c.id},h('summary',null,({fact:'陳述',inference:'推論',unknown:'尚未確認'}[c.kind])+' · '+c.statement),c.reasoning?h('p',null,c.reasoning):null,c.resolution?h('p',null,'相反證據處理：'+c.resolution):null,c.evidence.map((e,i)=>h('div',{key:i},h('small',null,({supports:'支持',contradicts:'相反證據',context:'背景'}[e.relation])+' · '+(task.sources.find(s=>s.id===e.sourceId)?.title||e.sourceId)),h('blockquote',null,e.quote))))):h('p',null,'尚未整理論點。')),
     task.comparison?h('section',null,h('h2',null,'方案比較'),task.comparison.options.map(option=>h('div',{key:option},h('h3',null,option),h('ul',null,task.comparison.criteria.map(criterion=>{const cell=task.comparison.assessments.find(c=>c.option===option&&c.criterion===criterion);return h('li',{key:criterion},h('strong',null,criterion+'：'),cell.claimIds.map(id=>{const claim=task.claims.find(c=>c.id===id);return claim?claim.statement+(claim.kind==='unknown'?'（尚未確認）':''):id}).join('；'))}))))):null,
     h('section',null,h('h2',null,'核查與交付'),task.review?h(React.Fragment,null,h('p',null,task.review.ready?'交付條件與證據連結檢查通過。':'仍有待處理項目。'),h('p',null,task.review.note),h('ul',null,[...task.review.errors,...task.review.warnings].map((text,i)=>h('li',{key:i},text)))):h('p',null,'尚未核查。'),task.deliveries.map(report=>h('p',{key:report.revision},h('a',{href:report.url,download:true},(report.partial?'部分成果':'完整報告')+' · 下載版本 '+report.revision))),h('small',null,'引用可追溯不代表來源必然正確；請同時閱讀推論、限制與分歧。'))
    ))))
 }
 return {inject:['slots'],apply(ctx){
  ctx.effect(()=>ctx.slots.inject('sidebar.panellist',()=>ctx.slots.register({name:'sidebar.panellist',id:'knowledge-work',order:36,label:'知識工作'},()=>h('span',{'aria-hidden':true},'▤'))))
  ctx.effect(()=>ctx.slots.inject('main',()=>ctx.slots.register({name:'main',key:'knowledge-work'},()=>h(Workbench))))
 }}
}})
